import time
from prana.models import Building
b = Building()
f = b.append_floor()
c1 = f.append_corridor(1)
c2 = f.append_corridor(2)
print("MAX WATTS", f.max_watts())
print("CURRENT WATTS", f.current_watts())
a1 = c1.append_appliance(1)
a2 = c1.append_appliance(2)
a3 = c2.append_appliance(1)
a4 = c2.append_appliance(1)
a5 = c2.append_appliance(1)
s1 = c1.append_sensor(1)
b.boot()
print("CURRENT WATTS", f.current_watts())
b.register_activity(0, 0, 0)
print("CURRENT WATTS", f.current_watts())
print("Expendable AC State", a3.status)
time.sleep(30)
b.refresh()
print("CURRENT WATTS", f.current_watts())
print("Expendable AC State after 30 secs", a3.status)
time.sleep(31)
b.refresh()
print("CURRENT WATTS", f.current_watts())
print("Expendable AC State after 61 secs", a3.status)
